package com.example.moreculture.db

import android.content.Context
import android.util.Log
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import org.osmdroid.util.GeoPoint

class PopulateDB(private val applicationContext: Context){

    // Callback interface for database population
    interface PopulateDbCallback {
        fun onDatabasePopulated()
    }

    // Populate the database with test data
    fun populateDB(mainViewModel: MainViewModel, callback: PopulateDbCallback? = null){
        CoroutineScope(Dispatchers.IO).launch {
            val places = createTestPlaces()
            val events = createTestEvents()
            val tags = createTags()
            val user = createTestUser()
            val eventTags = mapOf(
                1 to listOf(1, 7,16,13), // Event 1 has tags "Music" and "Festival"
                2 to listOf(3, 6, 4, 15, 16), // Event 2 has tags "Art" and "Exhibition"
                4 to listOf(1, 6,16,13),
                5 to listOf(1, 6, 16, 13),
                6 to listOf(1, 7, 16, 13, 14,12),
                7 to listOf(1, 6, 16, 13, 14,12),
                8 to listOf(1, 7, 16, 13, 14,12),
                9 to listOf(1, 6, 16, 13, 12),
                10 to listOf(1, 6, 16, 13, 14,12, 15),
                11 to listOf(1, 6, 16, 13, 12, 15),
                12 to listOf(1,2, 6, 16, 13, 14,12,15),
                13 to listOf(1, 6, 16, 13, 12, 15),
                14 to listOf(8, 10, 16, 13, 14,12, 15),
                15 to listOf(1, 6, 16, 13, 12, 15),
                16 to listOf(5, 7, 16, 13,  12),
                17 to listOf(5, 7, 16, 13, 14, 12),
                18 to listOf(5, 7, 16, 13,  12, 15),
                19 to listOf(1, 7, 16, 13, 14, 12, 15),
                20 to listOf( 2,  13,  12),
                21 to listOf( 2,  13,  12, 7, 15),
                22 to listOf( 2,  13,  12, 7, 15),
                23 to listOf( 2,  13,  12, 7, 15),
                24 to listOf( 2,  13,  12, 7, 15),
                25 to listOf( 2,  13,  12, 7, 15),
                26 to listOf( 10,  13, 12, 4, 11, 16),
                27 to listOf(  13, 12, 1, 11, 16, 15),
                28 to listOf(  13, 12, 1, 11, 16, 15),
                29 to listOf( 10,  13, 12, 4, 11, 16),
                30 to listOf( 10,  13,  4, 11),
                31 to listOf( 10,  13, 12, 8, 11 ),
                32 to listOf( 1, 6, 13, 12, 11,  15),
                33 to listOf( 10,  13, 12, 8, 11),
                34 to listOf( 1, 6, 13, 12, 11,  15),
                35 to listOf( 10, 6, 13, 12, 11),
                36 to listOf( 10, 6, 13, 12, 11,  15),
                37 to listOf( 1, 7, 13, 12, 11, 16),
                38 to listOf( 1, 7, 13, 12, 11, 16),
                39 to listOf( 1, 7, 13, 12, 11, 16),
                40 to listOf( 2, 6, 13, 12, 11, 16),
                41 to listOf( 10, 6, 13, 12, 11, 16),
                42 to listOf( 4,3, 6, 13, 12, 11, 16),
                43 to listOf( 5, 7, 13, 12, 11, 16),
                44 to listOf( 10, 5, 13, 12, 11, 16),
                45 to listOf( 3, 4, 13, 12, 11, 16, 15),
                46 to listOf( 3, 4, 13, 12, 11, 16, 15),
                47 to listOf( 3, 4, 13, 12, 11, 16, 15),
                48 to listOf( 3, 4, 13, 12, 11, 16, 15),
                49 to listOf( 3, 4, 13, 12, 11, 16, 15),
                50 to listOf( 3, 4, 13, 12, 11, 16, 15)
            )

            mainViewModel.insertTags(tags)

            places.forEach { place ->
                val geoPoint = GeoPoint(place.latitude, place.longitude)
                mainViewModel.insertPlace(place, geoPoint)
            }
            events.forEach { event ->
                val eventTagIds = eventTags[event.event_id] ?: emptyList()
                Log.d("MainActivity", "Event Tag IDs: $eventTagIds")
                mainViewModel.insertEventWithTags(event, eventTagIds)
            }

        }
    }

    private fun createTestPlaces(): List<Place> {
        return listOf(
            Place(1, "COMEDIA Theater", "Die Eingänge ins Theater und zur Gastronomie sind stufenlos erreichbar. Aufgrund des historischen, denkmalgeschützten Gebäudes ist die Eingangstür (Flügeltür; Gesamtbreite: 135 cm; einzeln – links: 65 cm, rechts: 70 cm) relativ schwer und nach außen zu öffnen.\n" +
                    "Vor den Vorstellungen bemühen wir uns darum, die Tür offenzuhalten, um den Eintritt für Sie zu erleichtern.", 50.920695973786586, 6.955192871168382, "geopoint_data_1", "http://comedia-koeln.de/"),
            Place(2, "Theater am Dom", "Der Stammbaum des Theater am Dom führt zurück bis in den Herbst des Jahres 1949. Eine Handvoll Schauspieler, gründeten im in Solingen das Westdeutsche Zimmertheater. Während der folgenden Jahre, in denen im Hotel „Timp“ am Heumarkt und in der so genannten „Tönenden Partitur“, zwischen dem WDR und dem Café Reichard gespielt wurde, fanden auch regelmäßig Theateraufführungen englischer, amerikanischer, französischer und italienischer Autoren in den jeweiligen Kulturinstituten  statt. Nach vielen Stationen in Köln fand das Theater, unter der künstlerischen Leitung von Hubertus Durek, dann 1957 erstmals eigenen eigenen Theaterraum an die Komödienstrasse/Burgmauer, wo das Westdeutsche Zimmertheater sich mit Blick auf den Dom umbenannte. Das war die Geburt des THEATER AM DOM.", 50.938558547271434, 6.9515307609177155, "geopoint_data_2", "https://theateramdom.de/"),
            Place(3, "Theater der Keller", "Unser Spielplan widmet sich aktuellen, gesellschaftspolitischen Themen, die in Eigenentwicklungen und zahlreichen Ur- und Erstaufführungen umgesetzt werden.\n" +
                    "\n" +
                    "Ein Schwerpunkt im Spielplan ist die Zusammenarbeit mit jungen Regisseur:innen und Theaterkünstler:innen und ihrer Arbeit an einer gegenwärtigen Formensprache des Theaters.", 50.92341202725054, 6.981650354431737, "geopoint_data_3", "https://www.theater-der-keller.de/"),
            Place(4,"Oper Köln / Staatenhaus", "Der internationale Rang der Oper Köln hat sich seit der feierlichen Eröffnung des Opernhauses am Offenbachplatz 1957 immer wieder manifestiert. Damals traten den Kölner Produktionen wie zum Beispiel „Oberon“ mit Leonie Rysanek und Karl Liebl und der Uraufführung von Wolfgang Fortners „Bluthochzeit“ u. a. Gastspiele der Mailänder Scala mit Maria Callas und des Balletts der Pariser Opéra an die Seite. In die Ära von Oscar Fritz Schuh als Intendant und Wolfgang Sawallisch als GMD (1959 - 1964) fielen Ereignisse wie etwa die Inszenierung von Richard Wagners „Der Ring des Nibelungen“ in der Regie von Wieland Wagner. Eine profilierte Ensemblezusammensetzung ergänzt durch die gastweise Verpflichtung hochkarätiger Sängerprominenz ist seit jeher entscheidendes Kriterium für die Arbeit des Hauses. Mit dem Internationalen Opernstudio verfügt die Oper Köln zudem seit 1961 über die älteste Institution zur Förderung junger Talente dieser Art im deutschsprachigen Raum, von der zahlreiche Sängerkarrieren wie von Anne Schwanewilms, Helen Donath, Samuel Youn oder Matthias Klink ausgingen.", 50.945856064471535, 6.973570460330295,"geo.4", "http://www.oper.koeln/de/" ),
            Place(5,"Kölner Philharmonie", "5", 50.9406908651576, 6.960673158594298, "geo.5", "http://koelner-philharmonie.de/"),
            Place(6, "Schauspiel Köln", "Hinter dem Label THEATER • STADT • SCHULE steckt unsere theaterpädagogische Abteilung, die künstlerische und bildungspolitische Impulse in der gesamten Stadt setzt – für, von und mit einer Vielzahl von Menschen. Eine Vision, die über die klassische Spielplanvermittlung hinausgeht: Wir versuchen, die Expertise des Publikums und der Öffentlichkeit hervorzuheben, kreativen Austausch zu initiieren und Räume für eigene Theatererfahrungen zu schaffen.", 50.96752531345752, 7.013383168386723, "geo.6", "http://www.schauspiel.koeln/"),
            Place(7, "Freies Werkstatt Theater Köln", "Das FWT: Freies Werkstatt Theater ist Ort des Austauschs und der künstlerischen Auseinandersetzung mit der Gegenwart. Seit seiner Gründung 1977 ist es eine feste Größe der freien Theaterszene Kölns. An der Schnittstelle von Theater, Performance und Medienkunst entwickelt das FWT: eigene Produktionen und arbeitet mit freien Künstler:innen und Gruppen zusammen. Unter dem Label Focus on: setzt sich das Haus, beginnend mit der Spielzeit 2024/25, in Themenreihen künstlerisch mit globalen Herausforderungen und gesellschaftlichen Spannungsfeldern auseinander. Darüber hinaus stellen wir außergewöhnliche Produktionen zeitgenössischer Dramatik vor. Ergänzt wird das Programm durch Talks und Lesungen sowie Inszenierungen für junges Publikum. Das FWT: steht in gemeinnütziger Trägerschaft und wird institutionell gefördert durch die Stadt Köln und das Land Nordrhein-Westfalen.", 50.91928107086956, 6.959148998138673, "geo.7", "https://www.fwt-koeln.de/"),
            Place(8, "Theater Bonn – Schauspielhaus", "Im 19. Jahrhundert bauten sich die Bürger der Stadt Bonn ein erstes Theater, das unabhängig zur musischen und künstlerischen Bildung beitragen sollte. Ganz ähnlich waren die Beweggründe für den damals noch eigenständigen Kurort Bad Godesberg, der zunächst für Gastspiele, später auch für ein eigenes Ensemble eine Spielstätte schuf. Heute leistet das städtische Mehrspartenhaus mit rund 500 Veranstaltungen pro Jahr einen wesentlichen Beitrag zum kulturellen Leben der Stadt sowie der gesamten Region. Neben zahlreichen Eigenproduktionen der Opern- und Schauspielsparte zählen auch die Gastspielreihen Highlights des Internationalen Tanzes und Quatsch keine Oper! fest zum Programm.", 50.68328590189251, 7.1539228209308785, "geopint8", "https://www.theater-bonn.de/"),
            Place(9,"Theater Bonn – Opernhaus", "Im Jahre 1826 errichteten Bonner Bürger auf eigene Initiative das erste Schauspielhaus der Stadt. 1848 kam es zu einem Neubau am Wilhelmsplatz, der ab 1902 ein eigenes Schauspiel- und ab 1935 ein eigenes Opernensemble beheimatete. 1944 wurde das Theater in der Theaterstraße vollständig von Bomben zerstört. Nach dem Krieg diente ein provisorisch hergerichteter Saal im Bürgerhaus als Theater. Auch wenn Bonn als Bundeshauptstadt, vor allen Dingen in den ersten Jahren, ein großes Provisorium war, musste nach einiger Zeit eine langfristige Lösung und ein neues Gebäude her. 1959 wurde dann im Rahmen eines Wettbewerbs der Auftrag für den Neubau eines Gebäudes ausgeschrieben: Es sollte ein neues Theater entstehen. Die Architekten Klaus Gessler und Wilfrid Beck-Erlang bekamen 1960 den Auftrag zum Bau erteilt – und nahmen ihren Auftrag sehr ernst.", 50.73704220505525, 7.106505083271689, "geo9", "https://www.theater-bonn.de/"),
            Place(10, "Kunstmuseum Bonn Museumsmeile", "Das Kunstmuseum Bonn gehört zu den großen, bundesweit beachteten Museen für Gegenwartskunst. Sein 1992 eröffneter, von dem Berliner Architekten Axel Schultes entworfener Neubau zählt deutschlandweit zu den wichtigen Museumsbauten der letzten Jahrzehnte.\n" +
                    "\n" +
                    "Im Mittelpunkt des Hauses steht die rund 9.000 Werke umfassende Sammlung des Kunstmuseums Bonn mit ihrem zentralen Werkkonvolut zu August Macke und der Kunst der Rheinischen Expressionisten sowie die bedeutende Sammlung zur Kunst in Deutschland nach 1945 mit Schwerpunkt auf der Malerei, Fotografie und zeitbasierten Medien. Besonderes Kennzeichen des bundesweit einmaligen Profils ist die Konzentration auf eine überschaubare Anzahl herausragender Künstler:innen, deren Werk in großangelegten Künstler:innenräumen gezeigt wird. Die international ausgerichteten thematischen und monografischen Ausstellungsprojekte werden in der Regel aus einem engen Bezug zum Sammlungskontext entwickelt.", 50.71538501082714, 7.120922224874621, "geo10", "https://www.kunstmuseum-bonn.de/de/")

        )
    }



    private fun createTestEvents(): List<Event> {
        return listOf(
            Event(1, 1, "Marjan, der letzte Löwe Afghanistans", "Der junge Löwe ist zwei Jahre alt, als er im Jahr 1978 als Geschenk Deutschlands nach Afghanistan gebracht wird. Aufgrund seiner Einzigartigkeit und Schönheit nennen seine Pfleger ihn liebevoll “Marjan” (persisch für \"Koralle\"). Der Kabuler Zoo ist einer der schönsten Zoos der Region, eine Oase der Fülle und des Friedens inmitten der Stadt. Marjan wächst unter der Bewunderung aller auf. Gemeinsam mit seiner Löwin Chucha und seinem Pfleger Sher Agha führt Marjan ein glückliches Leben."+
                    "Doch schon ein Jahr später bricht in Afghanistan Krieg aus – das Leben der Tiere des Zoos verändert sich schlagartig und schon bald muss auch der Löwe Marjan die schrecklichen Auswirkungen der langen kriegerischen Auseinandersetzungen spüren. Er erlebt die Besetzung Afghanistans durch die Sowjetunion, den Bürgerkrieg und schließlich die Schreckensherrschaft der Taliban. Er erlebt Verletzung, Hungersnot, Ungerechtigkeit und Demütigung – und doch gibt er nie auf. " +
                    "Die berührende Lebensgeschichte des Löwen Marjan, die von Liebe und Tapferkeit in schweren Zeiten handelt, wird hier für Kinder und Familien mit Humor und Poesie erzählt. Ernste Themen, wie Krieg, Hungersnot, Gerechtigkeit und Freiheit werden Kindern und Erwachsenen in diesem Stück mit Liebe und Feingefühl nähergebracht.", "https://www.comedia-koeln.de/media/rex_800/homepage_0000_marjan_afghanistan_c_morteza_herati_1.jpg", "Do 19.09.2024", "10:30", 0.0),
            Event(2, 1, "Anleitung zur Bewusstwerdung", "FLINTA steht für Frauen, Lesben, Inter-, Nicht-binäre, Trans- und Agender-Personen und umfasst eine vielfältige Gruppe, deren Erfahrungen und Herausforderungen oft im gesellschaftlichen Diskurs übersehen werden. Diese Installation zielt darauf ab, ihre Stimmen hörbar und ihre Lebensrealitäten sichtbar zu machen."
                    + "Die Installation bietet durch Geschichten, Gedichte, Gespräche und Klänge Einblicke in das Leben und die Perspektiven der FLINTA-Gemeinschaft. Die verschiedenen Stationen, die strategisch in der Stadt verteilt sind, beleuchten unterschiedliche Aspekte des Lebens dieser Personen. Das Publikum wird ermutigt, aktiv zuzuhören und sich mit den Themen auseinanderzusetzen.", "https://interfemme.de/2024-archiv-des-ueber-lebens/thumbnail.png", "19.,20.,21.,22.09.2024", "19:00", 9.95),
            Event(3, 1, "WASIHRWOLLT", "in einer Bearbeitung von Manuel Moser nach William Shakespeare - Kölner Theaterpreis 2023", "https://sommer.koeln/wp-content/uploads/2024/06/Was_ihr_wollt_Foto_Christopher_Horne-1700x956.jpg", "20.,21.,25.,25.09.2024", "20:00 ", 17.00),
            Event(4,1, "Mädchenschrift", "Ein Monolog von Özlem Özgül Dündar", "https://i.vimeocdn.com/video/1840083826-f0287071fe384c5dd6e5aae32e9647bfe18e2935e62a80af2bb623c561f378b5-d.jpg?mw=1100&mh=619&q=70","22.,23.,24.09.2024", "19:00", 17.00),
            Event(5,1, "Titanic","Schöne Menschen spielen große Gefühle von Bettina Hamel, Tobias Krechel, Birte Schrein, Stefan A. Schulz, Julia Wieninger", "https://theatergemeinde-koeln.org/datenbankbilder/koeln/Schauspiel/Comedia/Titanic_2024/Titanic%201_c_Comedia%20Theater.jpg", "21.,22.,23.09.2024", "19:00", 17.00 ),
            Event(6, 2, "ACHTSAM MORDEN", "Björn Diemel wird von seiner Frau gezwungen, ein Achtsamkeits-Seminar zu besuchen, um seine Ehe ins Reine zu bringen, sich als guter Vater zu beweisen und die etwas aus den Fugen geratene Work-Life-Balance wieder herzustellen. Denn Björn ist ein erfolgreicher Anwalt und hat dementsprechend sehr wenig Zeit für seine Familie. Der Kurs trägt tatsächlich Früchte und Björn kann das Gelernte sogar in seinen Job integrieren, allerdings nicht ganz auf die erwartete Weise. Denn als sein Mandant, ein berüchtigter Großkrimineller, beginnt, ihm ernstliche Probleme zu bereiten, bringt er ihn einfach um — und zwar nach allen Regeln der Achtsamkeit.", "https://theateramdom.de/fileadmin/user_upload/Achtsam-morden-Header-TAD-m-sq1.jpg", "05.09.2024 - 10.11.2024", "15:00", 38.0),
            Event(7,2,"AUF EIN NEUES", "Obwohl geschieden und alleinerziehend, hat Cathrin dank ihres Durchsetzungsvermögens Karriere in ihrem Beruf gemacht. Weniger erfolgreich ist sie in ihrer Karriere als Mutter ihrer Tochter Sarah, die sich von der dominierenden, nur am Erfolg orientierten Mutter vernachlässigt, gegängelt und unterdrückt fühlt und zur ewigen Studentin verkommt." + "Als Cathérine Heilig Abend vor ihrer Wohnungstür über Michel stolpert, einen abgerissenen und angetrunkenen Clochard, der sich vor der Kälte in das schicke Haus geflüchtet hat, schmeißt sie ihn erbarmungslos raus. Sarah ist empört, sie beschimpft ihre Mutter als herzloses Monster, das zu keiner Liebe, geschweige denn Nächstenliebe fähig sei. Um das Gegenteil zu beweisen, holt sie den Penner zurück und lädt ihn ein, Weihnachten zusammen mit ihnen zu feiern und schnell stellt sich die Frage, wer eigentlich verwahrlost ist….", "https://theateramdom.de/fileadmin/user_upload/Auf-ein-Neuesr-TAD-m-sq2.jpg", "05.09.2024 – 10.11.2024", "19:00", 38.00),
            Event(8, 2,"KARDINALFEHLER", "Ein vorbildliches Bistum irgendwo in Deutschland. Sauber, kaum Kirchenaustritte, absolut skandalfrei. Der Bischof ein energischer Aufklärer, der alle dunklen Schatten der Vergangenheit entschieden bekämpft und aufarbeitet. Ein Reformer, wie alle sich ihn wünschen." + "Daher wird der Papst das Bistum als Höhepunkt seiner Reise besuchen, die bekannteste Reliquie der Diözese segnen und eine Nacht im bischöflichen Palast verbringen. Doch während der Vorbereitungen auf den Besuch des Heiligen Vaters, stolpert ein Skandal in Person einer jungen Frau herein, der alle mitzureißen droht…" + "eine Co-Produktion mit dem Theater an der Kö, Düsseldorf", "https://theateramdom.de/fileadmin/user_upload/Kardinalfehler-TAD-m-sq1.jpg", "30.01.2025 – 06.04.2025", "20:00", 38.00),
            Event(9,2,"TOC TOC", "Toc Toc ist die spanische Bezeichnung für „einen Vogel haben“, einen Spleen. Fünf Personen mit einem zwanghaften Tick treffen nacheinander im Wartezimmer eines berühmten Psychotherapeuten ein. Da der Arzt im Zug in einer Strecken-Sperrung hängt, werden Sie miteinander konfrontiert, weil sie notgedrungen warten müssen, Um sich das Warten auf den Arzt zu verkürzen, informieren sich alle zunächst widerwillig über ihre jeweilige Störung und plötzlich entwickelt sich das Ganze zu einer ungewollten Gruppentherapie. Allerdings kommen dabei Dinge zu Tage, die kein Therapeut herausgefunden hätte und die heilsamer sind als alle gedacht haben.…", "https://theateramdom.de/fileadmin/user_upload/TOCTOC-TAD-m-sq7.jpg", "10.04.2025 – 14.06.2025", "20:00, 17.00", 38.00),
            Event(10, 3, "Aufbruch. Vision. Horizont", "Ein performativer Abend über ein freies Theater in Köln","https://theater-der-keller.de/assets/images/a/AUFRUCH.VISION-HORIZONT_GP240534_c_ProPho_3688-144a5cd5.webp",  "Mi 18.09.-, Do 26.09.2024", "20:00", 23.60 ),
            Event(11, 3, "Im Namen der Freiheit – Taras Schewtschenko / В імʼя свободи- Тарас Шевченко", "Ein Porträt des ukrainischen Nationaldichters / портрет українського народного поета","https://theater-der-keller.de/assets/images/1/OrloffphotoDSC_8846%20Kopie%202-a62b8580.webp", "Sa 21.09.-, So 22.09., Mi 02.10., Sa 02.11.2024", "20:00", 23.60 ),
            Event(12, 3, "Schauspielstudio", "In diesem Format stellt sich die Schauspielschule DER KELLER in regelmäßigen Abständen mit szenischen und musikalischen Beiträgen aus aktuellen Arbeiten dem Publikum vor. Schüler*innen aller Jahrgänge spielen, singen, sprechen, brüllen, leiden ein Leben lang und geben von allem viel zu viel in ihren Szenen, Monologen, Ensemblearbeiten und Liedern. Werfen Sie mit „ein leben lang von allem viel zu viel“ einen Blick ins Innere der Ausbildungswelt.", "https://theater-der-keller.de/assets/images/3/IMG_0164-36b08328.webp", "Mi 25.09.2024", "20:00",12.00),
            Event(13, 3, "Ach, diese Lücke, diese entsetzliche Lücke", "Von der nackten Angst vor dem Spielen zum gefragten Burgtheaterschauspieler: Der erfolgreiche Schauspieler und Schriftsteller Joachim Meyerhoff erzählt in seinem dritten Roman autobiografisch von der Tragikomödie menschlicher Existenz.\n" +
                    "\n" +
                    "Gerade 20 geworden, zieht der Erzähler bei den Großeltern in Nymphenburg ein. Während seiner Zeit an der Schauspielschule in München lebt er in zwei komplett voneinander getrennten Welten. Im Alltag des Schauspielschulen-Horrors scheitert er immer wieder – an Stimmübungen, am Gesangsunterricht, an Tier-Improvisationen. Aus der Überforderung flieht er in die aus der Zeit gefallene Welt der Großeltern: Jeder Tagesabschnitt verläuft gleich und wird von Unmengen Alkohol begleitet – ein disziplinierter Kampf gegen die Leere des Daseins.", "https://theater-der-keller.de/assets/images/8/045_Luecke_cMEYER_ORIGINALS-919f1c8c.webp", "Fr 27.09.-, Fr 01.11.2024", "20:00",23.60),
            Event(14, 3, "Der Reichsbürger", "Wie viel ‚Reichsbürger‘ steckt in mir? Wie weit bin ich davon entfernt, eine zehn Zentimeter breite gelbe Linie um mein Grundstück zu ziehen?\n" +
                    "\n" +
                    "Die Stimme des Reichsbürgers Christian S. führt Sie per Audio-Walk durch Köln und provoziert Sie, eine neue Perspektive auf das Alltägliche einzunehmen. Sind Sie wirklich so frei, liberal und weltoffen, wie Sie glauben? Schauen Sie sich ihre Umgebung genau an. Am Ende des Walks treffen Sie auf den Reichsbürger selbst, und es beginnt eine tour de force zu den Themen Selbstverwaltung, Wege in die Unabhängigkeit, der Mensch im Naturzustand.", "https://theater-der-keller.de/assets/images/9/Unknown-30f2deca.webp", "Sa 28.09.-, So 06.10.-, Fr 11.10.-, Sa 12.10.2024", "19:30", 23.60),
            Event(15, 3, "Ich werde nicht hassen / I shall not hate", "Es ist an der Zeit, dass wir uns hinsetzen und endlich miteinander reden“ lautet einer der Schlüsselsätze im Theaterstück „Ich werde nicht hassen“ von Izzeldin Abuelaish. Es erzählt vom Alltag in Gaza, vom Warten an den israelischen Checkpoints, vom Familienleben zwischen Hoffnung und Verzweiflung und von den unfassbaren Folgen von Gewalt.\n" +
                    "\n" +
                    "„Am 16. Januar 2009 um 16:45 Uhr wurden israelische Panzergranaten in das Schlafzimmer meiner Töchter gefeuert“, erzählt der palästinensische Gynäkologe. „Bessan, Aya und Mayar waren sofort tot, mit ihnen ihre Cousine Noor. Weil das israelische Militär Journalisten den Zugang nach Gaza verboten hatte, gab ich einem israelischen Fernsehreporter jeden Tag ein Telefoninterview. Minuten nach dem Angriff rief ich ihn beim Sender an; er übertrug unser Telefonat in die Sendung. Die Nachricht ging blitzschnell um die Welt.\"", "https://theater-der-keller.de/assets/images/1/RBF_2325-8cd5c519.webp", "SA 28.09.2024", "20:00", 23.60),
            Event(16, 3, "Nils Karlsson Däumling", "Die Oper „Nils Karlsson Däumling“ nach dem Kinderbuch von Astrid Lindgren erzählt die Geschichte von einem kleinen Jungen namens Bertil, der viel Zeit allein zu Hause verbringen muss. In seiner Einsamkeit versucht er, sich die Zeit zu vertreiben. Auf einmal vernimmt er ein leises Klopfen. Direkt neben ihm, in einem Mauseloch, wohnt ein kleiner Däumling, der so alt ist wie Bertil, aber nur so groß wie ein Daumen. Nisse, so heißt der Däumling, verrät Bertil ein Geheimnis: Wenn er einen Zauberspruch singt, wird er genauso klein wie er. Gesagt, getan. Bertil und Nisse schließen Freundschaft, und da Nisse Hunger hat und friert, hat Bertil wunderbare Ideen, wie er ihm zu einem kuscheligen Zuhause im Mäuseloch verhelfen kann…\n" +
                    "\n" +
                    "Die kleine Oper für alle ab 3 Jahren übersetzt die beiden unterschiedlichen Sphären – die Welt der Menschen und die Miniaturwelt des Däumlings – in eine Komposition für Sopran und Violine. Die Violine verkörpert dabei das Zauberwesen. Die fein gestaltete Mini-Oper lässt die zuschauenden Personen durch Gesang und Spiel aktiv an der Handlung teilhaben. Erstmalig besucht die Kinderoper Köln mit dieser mobilen Oper gezielt auch inklusive und vollstationäre Einrichtungen für Menschen mit und ohne Behinderung, mit besonderen sozialen Schwierigkeiten sowie intergenerative Gruppen von Kindern und Menschen mit Demenz. Ein umrahmendes Workshopprogramm, in dem die Teilnehmenden selbst musikalisch-spielerisch aktiv werden, erweitert das Angebot für alle jungen und älteren Menschen, die keine Kinderopernvorstellung im Opernhaus besuchen können.", "https://www.oper.koeln/media/filer_public_thumbnails/filer_public/82/42/82429a04-551c-403e-8b6c-c82e4facc9ab/daumling_vorschau.jpg__630x840_q85_crop_subsampling-2_upscale.jpg", "12.09-, 14.09-, 22.09.2024", "15:00", 22.00),
            Event(17,4, "Soiree mit öffentlicher Probe", "Gewinnen Sie vorab einen exklusiven Eindruck von Werk und Inszenierung. Hier erleben Sie das Produktionsteam im Gespräch, erfahren interessante Aspekte über Regieansätze, die musikalischen Besonderheiten eines Werkes oder auch über die Gestaltung der Bühne und Kostüme und dürfen anschließend bei einer Probe hautnah und live dabei sein!\n" + "Eine Anmeldung ist nicht erforderlich.", "https://www.oper.koeln/media/filer_public_thumbnails/filer_public/8a/78/8a7866a9-c7b8-4359-a8c2-4da301177c88/351_teresa_rothwangl_fotografin_trf1133_veranstaltungsbild.jpg__630x840_q85_crop_subject_location-3440%2C990_subsampling-2_upscale.jpg", "25.09-, 28.09-, 07.11.2024", "18:00", 22.00),
            Event(18,4, "Spielplanvorstellung für Pädagoginnen und Pädagogen", "", "https://www.oper.koeln/media/filer_public_thumbnails/filer_public/84/37/843745aa-4227-4ffa-b31c-cbc3e3a3bc9e/stuckmotive_online_1200x900_hoch_wolkenburg.jpg__630x840_q85_crop_subsampling-2_upscale.jpg", "26.09.2024", "17:00",22.00),
            Event(19, 4, "Ausschnitte aus: Nah am Wasser gebaut - Lieder, Chansons und Balladen", "", "https://www.oper.koeln/media/filer_public_thumbnails/filer_public/84/37/843745aa-4227-4ffa-b31c-cbc3e3a3bc9e/stuckmotive_online_1200x900_hoch_wolkenburg.jpg__630x840_q85_crop_subsampling-2_upscale.jpg", "02.10.2024", "18:00", 22.00),
            Event(20, 4, "Elektra", "Tragödie in einem Aufzug" + "Text von Hugo von Hofmannsthal" + "In deutscher Sprache mit Übertiteln", "https://www.oper.koeln/media/filer_public_thumbnails/filer_public/96/a4/96a4d51b-3b32-449f-bf93-ec77e5ebde04/stuckmotive_online_1200x900_hoch2.jpg__630x840_q85_crop_subject_location-450%2C600_subsampling-2_upscale.jpg", "06.10.-, 11.10-, 13.102024", "18:00", 15.00),
            Event(21,5,"PhilharmonieVeedel Baby", "In dieser musikalischen Performance kommen drei Elemente zusammen: Oboe, Tanz und Kanun (auch: Quanun) – fertig ist »Obotaqua«. Das Kanun ist eine Zither, die seit Jahrhunderten in der arabischen Musik zum Einsatz kommt. In dieser Musik- und Tanztheaterproduktion werden scheinbar ferne Klangwelten fantasievoll zusammengebracht. In der entspannten Atmosphäre der Bürgerzentren nähert sich die Kanun der Oboe an und verschmilzt mit dem Tanz im Raum zu einem fantasievollen Ganzen.", "https://www.koelner-philharmonie.de/media/filer_public_thumbnails/filer_public/00/e9/00e98b4e-dc1b-4a47-abc1-9c64751c4781/1a-pfaukanun_1.jpg__692x460_q85_crop_subject_location-1536%2C1024_subsampling-2_upscale.jpg", "Dienstag 17.09.2024", "15:00", 8.0),
            Event(22,5,"PhilharmonieLunch", "Erleben Sie in der Kölner Philharmonie Ihre kleine Pause vom Alltag – inspirierend, berührend, authentisch. Ein Ort voller Musik, für eine ungewöhnliche Mittagspause, eine Pause von den Geräuschen der Stadt oder einfach nur eine Pause vom Alltag."
                    + "PhilharmonieLunch wird von der KölnMusik gemeinsam mit dem WDR Sinfonieorchester und dem Gürzenich-Orchester Köln ermöglicht. ", "https://www1.wdr.de/orchester-und-chor/sinfonieorchester/orchester/kammerkonzert-662~_v-HintergrundL.jpg", "Donnerstag 19.09.2024", "12:00", 12.0),
            Event(23, 5, "Klangzauber - Măcelaru & Kanneh-Mason", "Mit nur 17 Jahren gewann Sheku Kanneh-Mason 2016 den Wettbewerb BBC Young Musician of the Year und zählt seitdem zu den Shootingstars der internationalen Klassikwelt. Wie gemacht für das virtuos-sinnliche Spiel des jungen Briten ist Schostakowitschs erstes Cellokonzert, hinter dessen tänzerischer Freude sich viele Momente großer emotionaler Tiefe verbergen. Das packende Werk mit seinen schillernden Klangfarben passt wunderbar zu den klingenden Märchen aus Tausendundeiner Nacht von Nikolaj Rimskij-Korsakow, in dem die Abenteuer von Sindbad und anderen Helden in einem fulminanten Tongemälde vorüberziehen.", "https://www1.wdr.de/orchester-und-chor/sinfonieorchester/orchester/chefdirigent/macelaru-130~_v-gseagaleriexl.jpg", "21.09.2024", "20:00", 64.00),
            Event(24, 5, "Verbotene Liebe", "Quatuor Diotima | Gürzenich-Orchester Köln | Matthias Pintscher", "https://theatergemeinde-koeln.de/datenbankbilder/koeln/Orchester/quatuor_diotima_c_michel_nguyen.jpg", "22.09.2024","11:00", 35.00),
            Event(25, 5, "Rising Stars: Benjamin Kruithof & Marco Sanna", "Nobel, füllig und sonor: Das Cello ist ein vielseitiges Instrument. Und auf einem ganz besonderen Cello spielt Rising Star Benjamin Kruithof – und demonstriert im Konzert gleich auch den ganzen Facettenreichtum seines tenoralen Streichinstruments.\n" +
                    "\n" +
                    "Gebaut im 18. Jahrhundert in den Werkstätten des legendären Giovanni Battista Guadagnini in Piacenza entlockt der junge luxemburgische Cellist, der eine Zeitlang auch in Köln studierte, seinem Instrument mit Nadia Boulanger einen impressionistischen Farbenreichtum, erweckt Benjamin Brittens bizarr-charaktervolle Sonate zum Leben und steigert sich in Rachmaninows Opus vom düsteren Beginn zum furiosen Abschluss. Dazu spielt er mit seinem Klavier-Duopartner Marco Sanna ein neues Werk der britischen Komponistin Sally Beamish, die sich als Bratschistin bestens auskennt mit Streichinstrumenten.\n" +
                    "\n" +
                    "»Rising Stars« ist ein Projekt der European Concert Hall Organisation (ECHO). Benjamin Kruithof wurde nominiert von Het Concertgebouw Amsterdam und Philharmonie du Luxembourg.", "https://www.koelner-philharmonie.de/media/filer_public_thumbnails/filer_public/99/93/9993b4c3-a766-4e01-bd01-2712554ed552/kruithof__benjamin_kaupo_kikkas_km187593.jpg__928x1080_q85_crop_subject_location-483%2C586_subsampling-2_upscale.jpg", "22.09.2024","16:00 ", 34.00),
            Event(26,6,"Theaterführung", "Regelmäßig laden wir unser Publikum ein, das Theater hinter den Kulissen zu erkunden. 90 Minuten berichten wir von der Entwicklung dieses besonderen Theaterortes auf einem ehemaligen Industrieareal, erklären, wie eine Inszenierung eigentlich entsteht, und geben Einblicke in die Abläufe und Geheimnisse der einzelnen Werkstätten und Abteilungen.","https://sk-6a25.kxcdn.com/content-images/size1080/image720/80b3a837a80161a51d1d173d12079dd4/10644/koeln_tot_stimmungsbilder_final_24.jpg", "Sa 21 Sep, So 20 Okt", "15:00", 5.0),
            Event(27,6,"Drahtseilakt /" + "Cambaz GÖSTERİSİ", "Vor gut 50 Jahren kommt es unter anderem bei Ford in Köln und bei Pierburg in Neuss zu »wilden« Streiks, initiiert von Migrant*innen. Sie lehnen sich auf gegen das rassistische, sexistische Lohnsystem und die ausbeuterischen Arbeitsbedingungen. Deniz Yılmaz ist Teil des Widerstands. Deniz ist Vorbild, Kollege, Verbündete, Freund*in, Mutter oder Großvater. Deniz ist eine fiktive Figur, entstanden aus den Erfahrungen und Erzählungen des Ensembles. Deniz ist jung und alt. Deniz kommt an und bricht auf. Deniz liebt und vermisst, ist aufmüpfig und angepasst, scheitert und gewinnt.\n" +
                    "Ein intergeneratives Ensemble begibt sich mit dem Publikum auf die Suche nach dieser fiktiven Figur. Was hat sich seit den Streiks getan und wie sieht Protest heute aus? Bei einem performativen Spaziergang über das Carlswerk-Gelände erzählen sie von Erinnerungen und Widerstand, von dem Mut, sich aufzulehnen, von Solidarität und der Sehnsucht danach, anzukommen.", "https://sk-6a25.kxcdn.com/content-images/size1080/image720/0e67d7a07047d41672e3725687dd940e/9417/l68b6044ana_lukenda.jpg", "Sa 21 Sep, So 22 Sep, Sa 19 Okt", "19.55", 15.00),
            Event(28, 6, "GRMPF", "Tröstlich ist: Die Bühnen Köln sind mit ihren Bauproblemen in dieser Stadt nicht allein. Das richtig Schlimme ist: Die Bühnen Köln sind mit ihren Bauproblemen in dieser Stadt nicht allein.\n" +
                    "\n" +
                    "Wallraf-Richartz, Waidmarkt, Römisch-Germanisches Museum, Zentralbibliothek, das Jüdische Museum und das Laurenz-Carré, die Nord-Süd U-Bahn und das Dom-Hotel. Ach, das Stadtarchiv darf nicht vergessen gehen.\n" +
                    "\n" +
                    "Mit Provisorien kennen die Kölner*innen sich aus, damit kann man hierzulande umgehen. Dafür hat nicht zuletzt auch der Dom gesorgt. Wurde die ewige Baustelle im Herzen der Stadt doch über die Zeit auf unnachahmliche Weise in die kölsche Weltsicht eingemeindet mit der Prophezeiung »Wenn der Dom fertig ist, geht die Welt unter«. Noch ist die Welt nicht untergegangen, noch wird in Köln saniert, wenn auch viel zu lange und zu horrenden Kosten. Nach dem zweiten gerissenen Eröffnungstermin am Offenbachplatz bleibt dem Theater derweil nichts übrig, als die ausgefallenen Feste gebührend zu feiern. Der Lappen muss schließlich hoch, gerade im Interim. GRMPF ist der Versuch einer Eröffnungsgala, wenn auch zur falschen Zeit und am falschen Ort. Eine musikalische Baustelle zwischen Hochkultur und Rohbau, die die Abgründe der speditiven Bauabwicklung ausleuchtet, Pfusch und Klüngel beim Sanieren im bröckelnden Bestand schonungslos aufdeckt und im Dschungel der Baupläne und -container Schuldige sucht. Wie es der Titel GRMPF vermuten lässt: Eine Lösung hat auch das Schauspiel Köln nicht, dafür aber viel Trost zu einem moderaten Preis (Selbsteinschätzung).", "https://sk-6a25.kxcdn.com/content-images/size1080/image720/fa9fcd6e16fa259704b24bfed7b29ffc/10643/grmpf015.jpg", "Sa 21 Sep,So 22 Sep, So 29 Sep", "19:30", 15.00),
            Event(29, 6, "NEULAND: THEATERSPIELE" + "FÜR ALLE FÄLLE", "In dieser offenen Fortbildung für Lehrkräfte, Pädagog*innen und Neugierige betreten wir gemeinsam Neuland und treffen uns zum Ausprobieren, Experimentieren, Fragen stellen. Zum Spielzeitbeginn bieten wir dafür ein buntes Buffet an Übungen unter dem Motto »Theaterspiele für alle Fälle«, von schnellen Energizer über Improklassiker bis zu Konzentrationsspielen – eben von Allem etwas. Die Theaterpädagog*innen Nina Mackenthun und David Vogel öffnen ihre Sammlung zum Losspielen und Mitnehmen. Der Workshop dauert drei Stunden und endet mit einer Materialsammlung für die direkte Umsetzung im Unterricht. In der Spielzeit 2024/25 finden abwechselnd Neuland-Termine im Schauspiel Köln, in der Oper Köln und in der Comedia statt, die unabhängig voneinander buchbar sind.", "https://sk-6a25.kxcdn.com/content-images/size1080/image720/0b096d2a08306a0929cbc14e74719510/8448/3_ad_vg.jpg", "Di 24 Sep", "17.30", 25.00),
            Event(30, 6, "We are family","Klytaimnestra, Königin von Mykene, muss mit ansehen, wie ihr Mann Agamemnon die gemeinsame Tochter Iphigenie opfert. Ihr Blut tauscht er gegen günstigen Fahrtwind ein, damit die griechische Flotte Richtung Troja in See stechen kann. Durch den Krieg gegen Troja soll die männliche Ehre seines Bruders Menelaos wiederhergestellt werden.", "https://sk-6a25.kxcdn.com/images/c11c4a6b8f20bbff3dceb458229ce5da/10557/img_3100_2.jpg", "Sa 28 Sep", "19.30", 40.00),
            Event(31, 7, "AUFTAKT FESTIVAL", "Aus Text wird Bild wird Sound wird wieder Text. Das auftakt versteht sich als Labor für Kollaboration, das jährlich Künstler:innen und Autor:innen nach Köln einlädt. Der Text in seinen diversen Erscheinungsformen steht dabei im Zentrum und ist gleichzeitig Ausgangspunkt für performative, sprach-künstlerische oder audio-visuelle Arbeiten. Mit thematisch wechselndem Fokus und begleitenden Workshops entwickelt sich das Festival jedes Jahr neu und lotet auf vielschichtige Weise die formalen Grenzen des literarischen Arbeitens aus.\n" +
                    "\n" +
                    "auftakt widmet sich in diesem Jahr der Arbeit und ihren Grenzbereichen, wo Arbeit performt, versteckt, verschoben oder unbemerkt gemacht wird.\n" +
                    "\n" +
                    "Gefördert durch das Ministerium für Kultur und Wissenschaft des Landes NRW, das Kulturamt der Stadt Köln und die Kunststiftung NRW", "https://www.fwt-koeln.de/fileadmin/_processed_/0/2/csm_auftakt_2024-FWT_1__1e0518a1d2.jpg", "21.-, 22.09.2024", "19:00", 0.0),
            Event(32, 7,"LIEBE/ EINE ARGUMENTATIVE ÜBUNG", "Comic-Held Popeye, der muskelbepackte Seemann, muss sich fortwährend mit allerlei Widersachern prügeln. Meist, um seine Dauerfreundin Olive Oyl aus höchster Not zu retten. In „Liebe“ ist alles anders: Autorin Sivan Ben Yishai macht den Sidekick Olive zur Hauptdarstellerin, und die beiden Comicfiguren werden zu Prototypen für heterosexuelle Paarbeziehungen von heute. Intimes wird öffentlich ausgesprochen, weil in die Geschichten des Körpers soziale Machtverhältnisse eingeschrieben sind. Als scharfsichtige Beobachterin ihres eigenen Liebeslebens seziert Olive die Ambivalenz zwischen weiblicher Selbstbestimmtheit und Sich-verlieren in alten Beziehungsmustern - um sich am Ende neu zu erfinden.", "https://www.fwt-koeln.de/fileadmin/user_upload/Stuecke/Liebe_eine_argumentative_UEbung/_c_niklasberg-1428.jpg", "26.09-, 11.10.2024", "20:00", 0.0),
            Event( 33, 7, "WORKSHOP pulk LEHR stelle", "Die Gruppe pulk fiktion und das Freie Werkstatt Theater Köln (FWT) laden zu einem künstlerisch-praktischen Workshop und Austausch mit Pädagog*innen ein. Im gemeinsamen Tun wird so die künstlerische Praxis von pulk fiktion erfahrbar. Dabei haben vor allem auch Fragen rund um das junge Publikum ihren Raum: Wie entwickelt man als Erwachsener ein Stück für Kinder? Was ist Überforderung, was Unterforderung eines Publikums? Welche Chancen verbergen sich im performativen Theater für junges Publikum? Und was bedeutet Augenhöhe im Theater von pulk fiktion?", "https://www.fwt-koeln.de/fileadmin/_processed_/2/5/csm_Webseite_PulkLehrStelle_613cd330b5.png", "01.10.2024", "17:00", 0.0),
            Event(34, 7, "Festival der Darstellenden Künste", "Vom 2. bis 4. Oktober 2024 wird Köln für drei Tage zum Ort für Tanz, Theater, zeitgenössischen Zirkus und Performance. Am 2.10. startet das Festival in der Kölner Südstadt, am 3.10. bespielen die Künstler:innen die rechte Rheinseite mit Schwerpunkt in Mülheim und Kalk und am 4.10. endet das Festival mit einem Riesenprogramm im belgischen Viertel, in Ehrenfeld und rund um den Ebertplatz.", "https://www.fwt-koeln.de/fileadmin/_processed_/9/d/csm_Background_breit_e4d3692203.jpeg", "02.10.2024", "20:00", 0.0),
            Event(35, 7, "POSTHUMAN CONDITION", "Frank ist Soldat und steuert im Homeoffice Drohnen, um Ziele in einer asiatischen Diktatur, dem Land „Eine Mitte ohne Ende“, zu bombardieren. Doch dabei trifft ihn ein alter kantonesischer Fluch: Sein Sohn wird ohne Po geboren. Frank begibt sich auf eine Reise nach Osten. Er will zu dem von ihm bombardierten Ort gelangen – auf der Suche nach Erkenntnis. Dabei gerät er immer tiefer in eine Welt der Geister, die ihn Geschichte, Schuld und Verantwortung neu verstehen lässt. In „Posthuman Condition“ beschreibt der 1975 in Hongkong geborene Theaterautor Pat To Yan Strukturen einer Diktatur und was „Menschsein“ heißt, wenn tiefgreifende gesellschaftliche und technologische Umwälzungen es bedrohen.", "https://www.fwt-koeln.de/fileadmin/_processed_/a/f/csm_Posthuman_Condition_FWT_A._Tepe_5c8ebfbd3d.jpg", "10.10.2024", "20:00", 0.0),
            Event(36, 7, "WIR MÜSSEN REDEN #3: VERZICHT", "Ob ökologische Zerstörung, andauernde und neue Kriege oder die zunehmende Konzentration von Reichtum in den Händen weniger – die großen Krisen unserer Gegenwart überschlagen sich und nehmen monströse Züge an. Die herrschenden Lösungen greifen nicht mehr, doch Neue scheinen kaum in Sicht. Die von demokratischen Regierungen ausgegebene vermeintliche Alternativlosigkeit des Bestehenden stärkt dabei rechte und autoritäre Kräfte in Deutschland und weltweit. Ressentiments, Ignoranz und Vereinfachung machen sich breit, der gesellschaftliche Dialog wird zunehmend schwieriger. Selbst innerhalb des progressiven Lagers tun sich tiefe Gräben auf.\n" +
                    "\n" +
                    "Mit unserem neuen Gesprächsformat „Wir müssen reden“ wollen wir das Theater als Ort radikaler Imagination herausfordern und neu entwerfen. Der Dialog findet in einer provisorischen Küche für alle im Foyer des FWT statt, in der Moderator Jascha Sommer mit den wechselnden Gästen gemeinsam für sich und das Publikum kochen. Im Anschluss an das Podium lädt eine lange Tafel zum gemeinsamen Essen und zur Diskussion auf Augenhöhe.\n" +
                    "\n", "https://www.fwt-koeln.de/fileadmin/_processed_/9/f/csm_Wir_muessen_reden__3_VERZICHT_5d9fbb02f8.png", "16.10.2024", "19:00", 0.0),
            Event(37, 8, "Fremd", "»Ich bin auf einem Friedhof geboren. Schmerz, der keinen Anfang kennt, der kein Ende kennt. […] Meine Mutter, mein Vater, meine Großmutter: Über-Lebende. Trauernde. Traurige. Lebenstraurige. Ich war ihr Lächeln. Lächelnde Traurigkeit.« \n" +
                    "\n" +
                    "FREMD erzählt die Geschichte eines Kindes. Es kommt in Frankreich als Sohn von Shoah-Überlebenden zur Welt. Die Familie ist staatenlos, heimatlos. Ein Leben in der Diaspora. In den Sechzigerjahren immigriert die Familie nach Deutschland. Ausgerechnet in das Land der Mörder, die fast die ganze Familie der Eltern ausgelöscht haben. Das Kind fühlt sich fremd. »Irgendwo im Nirgendwo lebe ich.« Wie soll man sich an diesem Ort ein Leben aufbauen? Wovon träumt man hier und wie schaut man an einem Ort in die Zukunft, wenn die Vergangenheit wie ein Schleier über allem liegt und die Gegenwart Ausgrenzung, Rassismus und Antisemitismus bedeutet? Die Familie hält zusammen. Vielleicht hält sie sich manchmal sogar zu fest. Das Kind fühlt sich ein Leben lang verantwortlich für die Eltern, bleibt Kind, auch als es schon längst erwachsen ist. Das Trauma lastet schwer auf der Familie, lässt sie nicht los. »Wenn ich Angst vor dem Fremden habe, wie viel Angst hat der Fremde vor mir. Und die Angst, die Angst ist mein Lebensgefährte.« Aber das Kind überlebt und versucht, weiter zu träumen.", "https://www.theater-bonn.de/media/filer_public/fb/a6/fba6e9ff-12fd-4ed3-ae41-09fada3c0861/fremd_hp2_0021matthias_jung_kopie.jpg", "17.-, 22.-, 24.09.2024", "20:00", 17.30 ),
            Event(38, 8, "Beethovenfest", "Darius Milhaud »La Création du monde«, Ballettmusik op. 81a | Kurt Weill Auszüge aus »Quodlibet« op. 9 | Robert Steidl »Wir versaufen unsrer Oma ihr klein Häuschen«, arr. von Iñigo Giner Miranda | Germaine Tailleferre Auszüge aus »Le Marchand d’oiseaux« | Otto Reutter »Es geht vorwärts« | Béla Bartók Auszüge aus »Tanz-Suite« Sz 77 | Dmitri Schostakowitsch Auszüge aus Klaviertrio Nr. 1 c-Moll op. 8 | mit dokumentarischem Material aus der Zeit Dmitri Schostakowitsch Sinfonie Nr. 1 f-Moll op. 10\n" +
                    "\n" +
                    "Wie klang Europa vor hundert Jahren? Das Beethoven Orchester Bonn geht zusammen mit Konzertgestalter und Beethovenfest-Fellow 2023 Iñigo Giner Miranda auf Entdeckungsreise – nicht nur musikalisch, sondern auch in Archiven und Zeitungen. Brüchige Demokratien, politische und kulturelle Revolutionen, Weltkriegsschock und Neubeginn: Eine brodelnde Zeit mit frappierenden Parallelen zur Gegenwart, die in der Collage aus Zeitdokumenten und Klang wieder lebendig wird.", "", "20.-, 22., 27.-, 28.09.2024","19.30", 38.00),
            Event(39,8,"Amphitryon", "Kannst du dich in mein eigen Ich verwandeln?\n" +
                    "Und wär imstande ich, nicht mehr ich zu sein?\n" +
                    "\n" +
                    "Jupiter, der höchste Gott und oberste »Womanizer« hat die schöne Alkmene zum Ziel seiner Verführungskünste erklärt und nimmt zu diesem Zweck die Gestalt ihres Ehemannes Amphitryon an. Gleichzeitig ärgert der Götterbote Merkur Amphitryons Diener, Sosias, indem er sich in diesen verwandelt und ihm seine Existenz streitig macht. Doch auch andere kommen auf diesselbe Idee. Also, wer ist denn nun eigentlich Sosias, der echte, der richtige Sosias: Scheinbar kann niemand das mit Fug und Recht von sich behaupten. Auch seine vorgebliche Ehefrau Cléanthis verliert sich, genau wie Alkmene, im Wechselspiel unterschiedlicher Aussagen.\n" +
                    "\n" +
                    "Diese und andere verwirrende Begegnungen erzeugen ein Identiätslabyrinth voller Täuschungen und Missverständnisse und führen so manchen und so manche an den Rand des Verstandes und zu Zweifeln an der eigenen Existenz. Alle Gewissheiten scheinen in diesem Spiel aufgelöst. Es erzeugt Ungewissheit statt Sicherheit. Ein Zustand, der uns modernen Menschen bekannt vorkommt. Nichts ist so, wie es sein sollte. Nichts ist so, wie es zu sein scheint. Einzelne gibt es plötzlich mehrfach. Bereits Moliéres Komödie ist ein raffiniertes Spiel um Schein und Sein, bei dem niemand unversehrt bleibt und die Textfassung des Theater Bonn versucht diese Verwirrung auf die Spitze zu treiben, um so die absurden Abgründe durch komödiantisches Spiel auszuleuchten.", "https://www.theater-bonn.de/media/filer_public/e7/a8/e7a8e4bd-a5f2-4edf-8aaa-98e76b945e70/ampithryon_hp1_0111_kopie.jpg", "20.-, 29.09.2024", "18:00", 17.30),
            Event(40,8, "Bad Bugs", "Insekten haben beim Menschen einen zweifelhaften Ruf. Sie stechen und beißen, verkriechen sich in Ecken und Ritzen und sind mit ihren spindeldürren Beinen, ihren Fühlern und Facettenaugen einfach nur ekelig, so die landläufige Meinung. Wer sich aber schon mal einen Goldkäfer aus der Nähe angeschaut hat, wird auch feststellen wie einzigartig schön so ein Insekt mitunter ist. Und viele Insekten sind dabei auch ausgesprochen nützlich und unverzichtbar für das ökologische Gleichgewicht. Käfer etwa lockern die Böden auf, kompostieren Abfälle, tragen zur Befruchtung von Pflanzen bei oder bekämpfen Schädlinge. Dennoch stehen viele Arten auf der roten Liste der gefährdeten Insekten ganz weit oben.\n" +
                    "\n" +
                    "Die »Bad Bugs«, die »bösen Käfer«, wollen ihrem schleichenden Untergang etwas entgegensetzen. Mit ihrer gleichnamigen Band reisen sie durch die Lande und kämpfen mit harter Schale, aber einem durchaus weichen Kern, gegen die Vernichtung ihrer Lebensräume. Ausgestattet mit Synthesizern, E-Gitarren und ihrer Stimme samplen sie auf öffentlichen Plätzen den eigenwilligen Underground Sound der Käferwelt und präsentieren uns musikalisch und aktionistisch ihre Sicht der Dinge. Sie fordern nicht weniger als unsere Solidarität im Kampf gegen die Zerstörung natürlicher Lebenräume und lassen die Zuschauenden teilhaben an der Um-Gestaltung hin zu einer vielartigen, lebendigen und lebenswerten Umgebung, in der sich Mensch und Tier gleichermaßen wohl fühlen können.", "https://www.theater-bonn.de/media/filer_public/5b/a7/5ba7d21f-e04f-47e6-9ba0-52d564033f77/bugs_1.jpg", "21.-, 22.-, 23.09.2024", "10:00", 17.30),
            Event(41, 8, "Wie man nach einem Massaker humanistisch bleibt in 17 Schritten", "Am 7. Oktober 2023 verübte die Terrorgruppe Hamas brutale Massaker gegen die israelische Zivilbevölkerung. Seitdem eskaliert der kriegerische Konflikt im Nahen Osten und auf der ganzen Welt. Die humanitäre Lage in Gaza ist lebensbedrohlich. Juden und Jüdinnen auf der ganzen Welt fühlen sich nicht mehr sicher. Antisemitische wie antimuslimische Positionen und Straftaten nehmen zu. Proteste werden von der Polizei geräumt. Die Fronten sind maximal verhärtet. Die Unterscheidung zwischen einer Geste der individuellen Solidarität und der politischen Differenzierung des Konflikts scheint vielen Menschen schwerzufallen. Wie soll man angesichts der Geschehnisse, angesichts der grausamen Bilder in den Medien, an einer individuellen und kollektiven Humanität festhalten?  \n" +
                    "\n" +
                    "In unmittelbarer Reaktion auf die terroristischen Anschläge der Hamas denkt die israelische Autorin Maya Arad Yasur über Bewältigungsstrategien und einen humanistischen Umgang mit der Gegenwart nach. Maya Arad Yasur appelliert dabei vor allem an die Empathie: »Ruf deine Freunde auf der anderen Seite der Grenze an, sie sind ebenfalls Humanisten, und auch sie glauben daran, dass die Menschen auf beiden Seiten der Grenze nur in Ruhe leben wollen.« ", "https://www.theater-bonn.de/media/filer_public/5b/77/5b77fbdd-4c2f-4aab-befd-be43c982fe6b/theater_bonn_matthiasjung17_schritte_vorab_0080_kopie.jpg", "22.09.2024", "18:00", 17.30),
            Event(42, 9, "INSTAWALK", "Die Bonner Oper wartet auf eine grundlegende Sanierung, aber sie ist trotzdem ziemlich fotogen: Die Tour für Instagramerinnen und Instagramer und alle, die gern fotografieren, führt von Makro zu Mikro: von der glänzenden Hülle bis zu edlen und überraschenden Details im Inneren. Es gibt viel Zeit zum Bildermachen und dazu überraschende Fun Facts: Wer weiß schon, was die Bonner Oper alles mit dem weltberühmten Sydney Opera House verbindet?", "https://www.theater-bonn.de/media/filer_public_thumbnails/filer_public/fd/e5/fde51503-2e4f-496a-96a8-59ffd7b05415/stadttheater-19_c_schafgans_archiv.jpg__670x500_q85_crop_subsampling-2_upscale.jpg", "28.09.2024", "15", 9.30),
            Event(43, 9, "Die Meistersinger von Nürnberg", "Woran erkennt man ein gutes Lied? Wer bestimmt die Kriterien, nach welchen geurteilt wird? Hört man dabei auf die alten Meister, die an den von ihnen einst erfundenen Regeln unnachgiebig festhalten, oder auf sein eigenes Herz, das im Liebeswahn die unmittelbare Wahrheit spricht? Gibt es vielleicht eine goldene Mitte?\n" +
                    "\n" +
                    "Drei Männer aus verschiedenen Generationen versuchen, Evas Herz bei einem Gesangswettbewerb zu gewinnen: Doch sie hat sich schon längst für einen der drei entschieden. Durch eine Reihe von Unglücks- und Glücksfällen, durch Täuschungen und listige Einfälle und schließlich doch durch fairen Wettkampf findet am Schluss der Oper das richtige Liebespaar zusammen. Offen bleibt nur die Zukunft: Wie geht man nun mit der Vergangenheit um und wer wird die neuen Spielregeln definieren?\n" +
                    "\n" +
                    "Trotz des ideologischen Missbrauchs dieses Titels durch das NS-Regime bleibt diese Oper eine der erfolgreichsten und beliebtesten Wagner-Opern auf den heutigen Spielplänen, weil sie über die plakative Interpretation hinaus mehrere Deutungsebenen zulässt. Die 1868 uraufgeführte Oper idealisiert das Bürgertum als Klasse mit dessen demokratischen Werten und dem Leistungsprinzip und macht sich über Mitläufer und Konformisten lustig. Außerdem beschäftigt sie sich mit der Frage nach der Kompromissbereitschaft und der Integration der besten Neuerungen ins bestehende System. In der Inszenierung von Aron Stiehl wird das Werk zu einem riesigen Festakt, im Rahmen dessen das Komische und das Ernsthafte im Stoff gleichermaßen zum Vorschein kommen.", "https://www.theater-bonn.de/media/filer_public_thumbnails/filer_public/c5/58/c55828f0-e7dc-4298-b130-87d0b1d06f8f/website-motive-meistersinger-von-nuernberg_2425.jpg__670x500_q85_crop_subject_location-603%2C445_subsampling-2_upscale.jpg", "03.10.2024", "16", 63.00),
            Event(44, 9, "U27-Preview", "Stückbeschreibung: Das Theater Bonn lädt Studierende aller Fachrichtungen zu einer exklusiven Preview ein. Live und vor Ort gibt es Interviews und Diskussionsrunden mit Mitwirkenden an unseren neusten Produktionen – mit Sängerinnen und Sängern, dem Regieteam, Maskenbildnerinnen und Maskenbildnern...", "https://www.theater-bonn.de/media/filer_public_thumbnails/filer_public/93/2e/932e2617-f983-4f70-a2fb-4790fa2a7bd9/website-motive-preview-2021.png__860x0_q85_crop_subject_location-602%2C441_subsampling-2_upscale.jpg", "16.10.2024", "18:00", 0.0),
            Event(45, 10, "Aufbruch in die Moderne", "Die Präsentation AUFBRUCH IN DIE MODERNE gliedert sich in drei Kapitel, die mit den malerischen und grafischen Werken der Sammlung der Klassischen Moderne – August Macke und die Rheinischen Expressionisten – einzelne Episoden der Geschichte zum Beginn des 20. Jahrhunderts erzählen und damit die Kunstwerke in einen größeren geschichtlichen Kontext stellen. Verfolgt wird hier keine strenge klassisch kunsthistorische Präsentationsform, sondern die Idee, dass Kunstwerke auf vielen Ebenen kommunizieren und Erkenntnis produzieren. Sie teilen uns etwas über ihr Entstehen, über die wissenschaftlichen Episteme der Zeit, über kunstwissenschaftliche Diskurse, über die Gesellschaften und die Menschen darin sowie über die heutigen Betrachter:innen mit. Wichtig hierbei ist die Beziehung der Kunstwerke zu den anderen Gegenständen, Werkzeugen, Erfindungen und Entdeckungen, die Ausdruck grundsätzlicher Einstellungen zur Welt sind. Jedem dieser Phänomene, seien sie bedeutend oder nichtig, liegt nicht nur diese Perspektivierung im Hinblick auf die Welt zugrunde, sondern es ist vielmehr diese Einstellung, die diese Phänomene erst entstehen lässt. Die Präsentation zeigt in Ausschnitten, was gleichzeitig auf verschiedenen Gebieten des kulturellen, wissenschaftlichen oder gesellschaftlichen Lebens geschah. Die Geschichte der Kunstwerke wird hier in unterschiedlichste Konstellationen der Dinge eingebunden.\n" +
                    "Dies bedeutet, dass Kunstwerke immer mehrdeutig interpretierbar sind und es sich daher um komplexe Gebilde handelt, die mit verschiedenen Bezugssystemen verbunden werden können. Unter Bezugssystemen verstehen wir sowohl kunstimmanente Aspekte als auch außerkünstlerische – kulturelle, geschichtliche, technische, wissenschaftliche etc. – Diskurse, Vorstellungen und Erkenntnisse sowie Fiktionen. Die Werke besitzen daher eine offene Struktur, die ihre Interpretation nicht zum Abschluss kommen lässt. Unsere Leseweise der Präsentation steht im Zeichen des AUFBRUCHS IN DIE MODERNE, des Aufbruchs in ein neues Jahrhundert, das große Veränderungen auf allen Ebenen des menschlichen Lebens bereithält.", "https://www.kunstmuseum-bonn.de/wp-content/uploads/2021/06/Aufbruch-in-die-Moderne_Apfelschale-und-Faecher_Titel-1.jpg", "27.06.2021 – 31.08.2025", "10:00", 7.00),
            Event(46, 10, "Raum für phantasievolle Aktionen", "Die Präsentation wirft einen umfassenden Blick auf die Sammlung der Kunst der Gegenwart, die in zwanzig Räumen aus ver\u00ADschiedenen Perspektiven neu präsentiert wird. Neben Malerei sind Installationen, Film und Fotografie zu sehen. Die Ausstellung umfasst für das Profil der Sammlung wichtige Werke sowie Neuerwerbungen, Schenkungen und Leihgaben aus Privat\u00ADsammlungen. Sie verbindet monografische und themati\u00ADsche Werkgruppen von Sigmar Polke bis Monika Baer, von Tamara Grcic, Shannon Bool, Norbert Schwontkowski bis John Bock. So entsteht ein kom\u00ADplexer Parcours der Werke: Äußere und innere Räume sind zu begehen, werden kartografisch vermessen, zu unsicheren Interieurs geöff\u00ADnet, der Körper wird zur Kampfzone erklärt, Gesich\u00ADter verwandeln sich in Masken, das Ich spielt ver\u00ADschiedene Rollen. Malerei zeigt sich als verworrenes Gewebe und glatte Fläche, ordentliche und unordentli\u00ADche Überlagerung, alchemis\u00ADtische Verschmelzung von Exotik und Populärkultur. Materialien führen ausge\u00ADdehnte Gespräche, Fotoserien sammeln die Welt in flexible Speicher, Malerei und Fotografie prüfen die Gleichzeitigkeit des Deutlichen und des Undeutlichen. Das Museum wird zum „Raum für phantasievolle Aktionen“ (Albert Oehlen).", "https://www.kunstmuseum-bonn.de/wp-content/uploads/2022/01/mittel_Oehlen-Albert-_Raum-fuer-phantasievolle-Aktionen-1983.jpg", "08.05.2022 – 31.12.2025", "11:00", 7.00),
            Event(47, 10, "KATHARINA GROSSE", "Katharina Grosse ist international bekannt für ihre expansiven Spray-Arbeiten, die sie vor Ort ausführt und dabei häufig den Außenraum mit einbezieht. Bislang wurde ihren im Atelier entstandenen Leinwandarbeiten weniger Beachtung geschenkt. Die Ausstellung widmet sich erstmals umfassend diesem Teil von Grosses Schaffen, von den Gemälden der späten 1980er Jahre bis zu ihren jüngsten Arbeiten.\n" +
                    "\n" +
                    "Grosses großformatige, ungemein kraftvollen Gemälde unterlaufen die konventionellen Beziehungen von Vorder- und Hintergrund, Oberfläche und Untergrund, Bildfläche und Bildrand und eröffnen neue Vorstellungswelten innerhalb und außerhalb des Kunstwerks. In einem ergebnisoffenen, schöpferischen Prozess, in dem die Malerei performative Züge annimmt, überdenkt Grosse grundlegende Fragen, die die Geschichte der Malerei lange Zeit definiert haben.\n" +
                    "\n" +
                    "Die Ausstellung gliedert sich in die zwei großen thematischen Felder Wiederholungen, Revisionen, Neufindungen und Risse, Brüche. Das Thema Wiederholungen, Revisionen, Neufindungen umfasst eine breite Palette von Gemälden, die seit den frühen 1990er Jahren entstanden sind, und veranschaulicht die zyklische Arbeitsweise der Künstlerin.\n" +
                    "\n" +
                    "Risse, Brüche konzentriert sich auf die verschiedenen Methoden, mit denen Grosse das Medium der Malerei aufbricht, um seine Grenzen zu erweitern. Dazu gehört u. a. die Einbeziehung natürlicher Materialien wie Erde und Äste, die das übliche Verhältnis zwischen Kunst und Natur neu interpretieren.", "https://www.tagesspiegel.de/images/10895923/alternates/BASE_1_1_W1000/1701958920000/katharina-grosse-warum-drei-toene-kein-dreieck-bilden-2023-albertina-wien-katharina-grosse-bildrecht-wien-2023-7.jpeg", "25.04.2024 – 22.09.2024", "11:00", 7.00),
            Event(48, 10, "Raum für Demokratie", "Der „Raum für Demokratie“ ist Ausstellungsraum und Werkstatt zugleich. Hier verbinden sich Perspektiven aus der Sammlung des Kunstmuseums Bonn mit denen der Besucher:innen.\n" +
                    "\n" +
                    "Anlässlich des 75. Jubiläums des Grundgesetzes widmet das Kunstmuseum Bonn einen Sammlungsraum dem Thema Demokratie.  Kunstwerke der vergangenen 75 Jahre blicken aus verschiedenen Zeiten auf die deutsche Geschichte, die Gesellschaft und auf demokratische Werte. Von Mai bis Dezember finden im Raum für Demokratie regelmäßig Workshops statt, die in der partizipativen Gestaltung des DigitalGuides des Kunstmuseums Bonn münden. Abrufbar über QR-Codes, fungiert der DigitalGuide im Raum für Demokratie als Plattform für eine mehrstimmige Kunstvermittlung. Die Besucher:innen kommen zu Wort, teilen und reflektieren ihre Assoziationen und Eindrücke. Zusätzliche Textimpulse im Ausstellungsraum regen zum Schreiben, Lesen und zu Gesprächen an.\n" +
                    "\n" +
                    "Die Liste der Künstler:innen umfasst Benjamin Bergmann, Joseph Beuys, Andreas Gursky, Paul Klee, Barbara Klemm, Erik van Lieshout, Sigmar Polke, Anys Reimann, Ulrike Rosenbach und Klaus Staeck.", "https://www.kunstmuseum-bonn.de/wp-content/uploads/2024/04/Werk_Reimann_LE-NOIRE-DE%E2%80%A6-XXXV-Photo-Johannes-Bendzulla_ohne-Rahmen.jpg", "25.05.2024 – 12.01.2025", "11:00", 7.00),
            Event(49, 10, "BRUNO GOLLER", "Lange hat man die Malereigeschichte des 20. Jahrhunderts als Konkurrenzkampf von Schulen und Stilen gedeutet und dabei übersehen, wie bestimmend gerade die Außenseiter für die Entwicklung der Kunst sein können. Zur Gruppe dieser eigenwilligen Einzelgänger gehört – trotz mancher Parallelen die sein Schaffen zur Kunst des Surrealismus und zur neuen Sachlichkeit aufweist – auch Bruno Goller.\n" +
                    "1901 in Gummersbach geboren und seit 1927 dauerhaft in Düsseldorf ansässig, entfaltet er in über siebzig Schaffensjahren eine magische Bildwelt, die, im Kontrast zur großen Zeitströmung der Abstraktion, von einem klaren Bekenntnis zur Gegenständlichkeit geprägt ist. Wir erkennen Häuser, Uhren, Hüte, Rosen, Schirme, Mäntel und, nicht zuletzt, Frauen, die in aller Regel typisiert und streng formalisiert wiedergegeben werden. Wenn auch gelegentlich Männer in seinen Gemälden auftauchen, so sind es doch die Frauen, die im Zentrum seiner Kunst stehen. In ihrer idolhaften Präsenz sind sie jedoch so wenig greifbar und ausdeutbar wie all die Gegenstände von denen sie umgeben sind.\n" +
                    "Welche tiefere Bedeutung führt all die Dinge im Bild zusammen? Sicher sind assoziative Verknüpfungen des Bildinventars punktuell möglich, doch sperren sich Gollers Gemälde gegen eine eindeutige Lesbarkeit. Sie verweigern sich letzten Endes dem Zugriff der Interpret:innen und gewinnen gerade daraus ihre Strahlkraft: die Magie des Rätselhaften.", "https://www.kunstmuseum-bonn.de/wp-content/uploads/2023/12/neues-Beitragsbild_Bruno-Goller-Frauenkopf-1957.jpg", "19.09.2024 – 19.01.2025", "11:00", 7.00),
            Event(50, 10, "Human AI Art Award 2024", "Der erste Human AI Art Award wird 2024 an die chinesisch-amerikanische Künstlerin Lauren Lee McCarthy vergeben. Der Preis ist eine gemeinsame Initiative des Kunstmuseums Bonn und der Deutschen Telekom und würdigt herausragende künstlerische Leistungen im Spannungsfeld zwischen Bildender Kunst und Technologie, insbesondere künstlicher Intelligenz.\n" +
                    "\n" +
                    "Für ihr prämiertes Werk „LAUREN“ beobachtete Lauren Lee McCarthy freiwillige Teilnehmerinnen und Teilnehmer eine Woche lang über ein Netzwerk von ferngesteuerten Kameras, Mikrofonen, Lautsprechern und anderen elektronisch gesteuerten Geräten. Die in Los Angeles lebende Künstlerin interagierte mit ihnen als eine persönliche virtuelle Sprachassistentin. So schaltete sie sich in das Leben der Bewohnerinnen und Bewohner ein, kommentierte, gab Ratschläge oder änderte die Beleuchtung. Sie wollte die bessere, die menschliche, persönliche Assistentin sein, die Bedürfnisse früh erkennt und auf die Individualität der Personen mit Humor und Empathie reagiert. Gleichzeitig drang sie als ständige Beobachterin in die Privatsphäre der Personen ein. Sie schuf daraus ein Dokumentarvideo, das nun in einer eigens für den Human AI Art Space umgestalteten Installation präsentiert wird. Die so entstandene ortsspezifische Arbeit „LAUREN: Anyone home?“ thematisiert die Spannung zwischen Selbstverständlichkeit, Vereinfachung, Zweifel und Neugier im Umgang mit KI-Technologien auf beeindruckende Art und Weise. Die Ausstellung findet im eigens für den Preis entworfenen ‚Human AI Art Space‘ statt, der im Außenbereich vor dem Museum auch ein architektonisches Zeichen setzt. Zur Preisverleihung und Eröffnung der Ausstellung wird Lauren Lee McCarthy anwesend sein und ihr Werk im Rahmen einer Performance aktivieren. Dabei können die Besucher mit der menschlichen Sprachassistenz interagieren und so Teil der Performance-Installation werden. Darüber hinaus wird die Installation an einigen zusätzlichen Terminen während der Laufzeit durch Performances aktiviert.", "https://www.telekom.com/en/media/media-information/archive/deutsche-telekom-and-kunstmuseum-bonn-human-ai-art-award-1075066", "17.11.2024 – 19.01.2025", "11:00", 7.00)



        )

    }

    private fun createTestUser() : UserAccount{
        return UserAccount(0,"David",20.00)
    }


    private fun createTags(): List<Tag> {
        return listOf(
            Tag(1, "Theater"),
            Tag(2, "Concert"),
            Tag(3, "Exhibition"),
            Tag(4, "Art"),
            Tag(5, "Opera"),
            Tag(6, "Modern"),
            Tag(7, "Classic"),
            Tag(8, "OpenAir"),
            Tag(9, "Creative"),
            Tag(10, "Workshop"),
            Tag(11, "DisabledParking"),
            Tag(12, "BicycleParking"),
            Tag(13, "PublicTransport"),
            Tag(14, "Subtitle"),
            Tag(15, "Accessibility"),
            Tag(16, "CarParking")
        )
    }
}